version: '3.5'

services:
  accounts:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - ganache
    volumes:
      - ./accounts/src:/app/src
      - ./accounts/config:/app/config
      - ./accounts/.babelrc:/app/.babelrc
    environment:
      BLOCKCHAIN_HOST: http://ganache
      BLOCKCHAIN_PORT: 8545
    networks:
      - nightfall_network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - accounts
      - offchain
      - zkp
      - database
    volumes:
      - ./api-gateway/src:/app/src
      - ./api-gateway/config:/app/config
      - ./api-gateway/.babelrc:/app/.babelrc
    ports:
      - '8001:80'
    environment:
      ACCOUNTS_HOST: http://accounts
      ACCOUNTS_PORT: 80
      DATABASE_HOST: http://database
      DATABASE_PORT: 80
      OFFCHAIN_HOST: http://offchain
      OFFCHAIN_PORT: 80
      ZKP_HOST: http://zkp
      ZKP_PORT: 80
    networks:
      - nightfall_network

  offchain:
    build:
      context: ./offchain
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - ganache
    volumes:
      - ./offchain/src:/app/src
      - ./offchain/build:/app/build
      - ./offchain/.babelrc:/app/.babelrc
      - ./offchain/__tests__:/app/__tests__
      - ./zkp-utils:/app/node_modules/zkp-utils
      - ./offchain/config:/app/config
    environment:
      AUTHENTICATION_API_HOST: http://api-gateway
      AUTHENTICATION_API_PORT: 80
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
    networks:
      - nightfall_network

  zkp:
    build:
      context: ./zkp
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - ganache
    volumes:
      - ./zkp/src:/app/src
      - ./zkp/build:/app/build
      - ./zkp/code:/app/code
      - ./zkp/.babelrc:/app/.babelrc
      - ./zkp/__tests__:/app/__tests__
      - ./zkp/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
      MERKLE_TREE_HOST: http://merkle-tree
      MERKLE_TREE_PORT: 80
      ZKP_CODE_VOLUME: nightfall_zkp-code-volume
    networks:
      - nightfall_network
      - merkle_tree_network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./ui/src:/app/src
      - ./ui/angular.json:/app/angular.json
      - ./ui/tsconfig.json:/app/tsconfig.json
    ports:
      - '8000:80'
    networks:
      - nightfall_network

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli --accounts=10 --defaultBalanceEther=1000
    ports:
      - '8545:8545'
    networks:
      - nightfall_network
      - merkle_tree_network

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - mongo-nightfall
    volumes:
      - ./database/src:/app/src
      - ./database/.babelrc:/app/.babelrc
      - ./zkp-utils:/app/node_modules/zkp-utils
      - ./database/config:/app/config
      - ./database/setup-mongo-acl-for-new-users.js:/app/setup-mongo-acl-for-new-users.js
    networks:
      - nightfall_network

  mongo-nightfall:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=nightfall
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mongo-nightfall-volume:/data/db
    networks:
      - nightfall_network

  truffle-offchain:
    image: ajmay/truffle:5.0.9
    environment:
      SOLC_VERSION: 0.5.8
      ETH_HOST: ganache
      ETH_GAS: 6000000
      ETH_GAS_PRICE: 20000000000
    volumes:
      - ./offchain/contracts:/truffle/contracts:delegated
      - ./offchain/migrations/:/truffle/migrations:delegated
      - ./offchain/build/contracts/:/truffle/build/contracts:cached
      - ./offchain/test/:/truffle/test:delegated
    depends_on:
      - ganache
    logging:
      options:
        max-size: 10m
    networks:
      - nightfall_network

  truffle-zkp:
    image: ajmay/truffle:5.0.9
    environment:
      SOLC_VERSION: 0.5.8
      ETH_HOST: ganache
      ETH_GAS: 6000000
      ETH_GAS_PRICE: 20000000000
    volumes:
      - ./zkp/contracts/:/truffle/contracts:delegated
      - ./zkp/migrations/:/truffle/migrations:delegated
      - ./zkp/build/contracts/:/truffle/build/contracts:cached
      - ./zkp/test/:/truffle/test:delegated
      - ./zkp/src/:/truffle/src:delegated
    depends_on:
      - ganache
    logging:
      options:
        max-size: 10m
    networks:
      - nightfall_network

volumes:
  mongo-nightfall-volume: {}
  zkp-code-volume:
    driver: local
    driver_opts:
      type: none
      device: $PWD/zkp/code/
      o: bind

networks:
  nightfall_network:
    name: nightfall_network
  merkle_tree_network:
    name: merkle_tree_network
